### ISSUE TITLE
After installation on OXID 6.2.0 "module" section in admin panel crashes

### ISSUE THREAD

**Issue by walldemar** [OXIDprojects/oxid-module-internals#130]
OXID 6.2.0 throw an error in log file:
`[2020-04-10 10:22:46] OXID Logger.ERROR: Function 'validateMetadataExtendSection' does not exist or is not accessible! (OxidCommunity\ModuleInternals\Core\ModuleStateFixer)
 ["[object] (OxidEsales\\Eshop\\Core\\Exception\\SystemComponentException(code: 0): Function 'validateMetadataExtendSection' does not exist or is not accessible! (OxidCommunity\\ModuleInternals\\Core\\ModuleStateFixer)\n at /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ce/source/Core/Base.php:84)\n[stacktrace]\n#0 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-community/moduleinternals/Core/ModuleStateFixer.php(679): OxidEsales\\EshopCommunity\\Core\\Base->__call('validateMetadat...', Array)\n#1 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-community/moduleinternals/Core/ModuleStateFixer.php(540): OxidCommunity\\ModuleInternals\\Core\\ModuleStateFixer->checkExtensions(Object(OxidCommunity\\ModuleInternals\\Core\\InternalModule), Array, Array)\n#2 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-community/moduleinternals/Core/ModuleStateFixer.php(693): OxidCommunity\\ModuleInternals\\Core\\ModuleStateFixer->_addExtensions(Object(OxidCommunity\\ModuleInternals\\Core\\InternalModule))\n#3 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-community/moduleinternals/Core/ModuleStateFixer.php(360): OxidCommunity\\ModuleInternals\\Core\\ModuleStateFixer->fixExtensions(Object(OxidCommunity\\ModuleInternals\\Core\\InternalModule))\n#4 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-community/moduleinternals/Core/ModuleStateFixer.php(107): OxidCommunity\\ModuleInternals\\Core\\ModuleStateFixer->restoreModuleInformation(Object(OxidCommunity\\ModuleInternals\\Core\\InternalModule), 'bestitamazonpay...')\n#5 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-community/moduleinternals/Core/InternalModule.php(250): OxidCommunity\\ModuleInternals\\Core\\ModuleStateFixer->fix(Object(OxidCommunity\\ModuleInternals\\Core\\InternalModule))\n#6 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ce/source/Application/Controller/Admin/ModuleList.php(72): OxidCommunity\\ModuleInternals\\Core\\InternalModule->getTitle()\n#7 [internal function]: OxidEsales\\EshopCommunity\\Application\\Controller\\Admin\\ModuleList->OxidEsales\\EshopCommunity\\Application\\Controller\\Admin\\{closure}(Object(OxidCommunity\\ModuleInternals\\Core\\InternalModule), Object(OxidCommunity\\ModuleInternals\\Core\\InternalModule))\n#8 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ce/source/Application/Controller/Admin/ModuleList.php(73): usort(Array, Object(Closure))\n#9 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ce/source/Application/Controller/Admin/ModuleList.php(59): OxidEsales\\EshopCommunity\\Application\\Controller\\Admin\\ModuleList->sortModulesByTitleAlphabetically(Array)\n#10 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ce/source/Application/Controller/Admin/ModuleList.php(38): OxidEsales\\EshopCommunity\\Application\\Controller\\Admin\\ModuleList->getInstalledModules()\n#11 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(465): OxidEsales\\EshopCommunity\\Application\\Controller\\Admin\\ModuleList->render()\n#12 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ee/Core/ShopControl.php(208): OxidEsales\\EshopCommunity\\Core\\ShopControl->_render(Object(OxidEsales\\Eshop\\Application\\Controller\\Admin\\ModuleList))\n#13 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(357): OxidEsales\\EshopEnterprise\\Core\\ShopControl->_render(Object(OxidEsales\\Eshop\\Application\\Controller\\Admin\\ModuleList))\n#14 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ee/Core/ShopControl.php(98): OxidEsales\\EshopCommunity\\Core\\ShopControl->formOutput(Object(OxidEsales\\Eshop\\Application\\Controller\\Admin\\ModuleList))\n#15 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(281): OxidEsales\\EshopEnterprise\\Core\\ShopControl->formOutput(Object(OxidEsales\\Eshop\\Application\\Controller\\Admin\\ModuleList))\n#16 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(142): OxidEsales\\EshopCommunity\\Core\\ShopControl->_process('OxidEsales\\\\Esho...', NULL, NULL, NULL)\n#17 /var/www/html/oxidproject/releases/releaseinit/vendor/oxid-esales/oxideshop-ce/source/Core/Oxid.php(27): OxidEsales\\EshopCommunity\\Core\\ShopControl->start()\n#18 /var/www/html/oxidproject/releases/releaseinit/source/index.php(16): OxidEsales\\EshopCommunity\\Core\\Oxid::run()\n#19 /var/www/html/oxidproject/releases/releaseinit/source/admin/index.php(12): require_once('/var/www/html/r...')\n#20 {main}\n"] []
`

**Comment by d3datadev** [comment]
Do you want to limit the package "oxid-esales/oxideshop-ce" in the dependencies to "6.1 - 6.3" in the last version, as long as the installation in OXID Compilation 6.2 still causes errors? Otherwise even more users will be annoyed.

You can create a dev-branch which is released for 6.2. But then the users will confirm this explicitly.

IMHO a general release for future shop packages ">= 6.1" is problematic for such a very system dependent module.

**Comment by keywan-ghadami-oxid** [comment]
Thanks for pointing this out.
Module internals seams not yet ready for oxid 6.2 and not officially supported by OXID eSales. Any support on this project is welcome. I am using it now also in oxid 6.2 and looking forward to contribute some improvements. 3.0.0-alpha6 is the version to got when using oxid 6.2 but be aware that it does not yet does it job in a proper way.

**Comment by d3datadev** [comment]
Hi,
we actually tested the branch "support-oxid-62" and most works fine after fixing https://github.com/OXIDprojects/oxid-module-internals/pull/131
