### ISSUE TITLE
EXCEPTION_SYSTEMCOMPONENT_CLASSNOTFOUND: ModuleExtensionCleanerDebug

### ISSUE THREAD

**Issue by adriankirchner** [OXIDprojects/oxid-module-internals#31]
https://github.com/OXIDprojects/oxid-module-internals/blob/3ef518018b36f7b4944dbca7e8202ed5ef19afdb/Core/ModuleStateFixer.php#L23

This dependency to oxid-console should get either removed or registered via composer. An a fresh CE 6.1.1 this results in:

```
OXID Logger.ERROR: EXCEPTION_SYSTEMCOMPONENT_CLASSNOTFOUND OxidProfessionalServices\OxidConsole\Core\Module\ModuleExtensionCleanerDebug ["[object] (OxidEsales\\Eshop\\Core\\Exception\\SystemComponentException(code: 0): EXCEPTION_SYSTEMCOMPONENT_CLASSNOTFOUND OxidProfessionalServices\\OxidConsole\\Core\\Module\\ModuleExtensionCleanerDebug at /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/UtilsObject.php:222)\n[stacktrace]\n#0 /var/www/oxid/source/oxfunctions.php(101): OxidEsales\\EshopCommunity\\Core\\UtilsObject->oxNew('OxidProfessiona...')\n#1 /var/www/oxid/source/modules/oxcom/moduleinternals/Core/ModuleStateFixer.php(23): oxNew('OxidProfessiona...')\n#2 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/UtilsObject.php(231): OxidCommunity\\ModuleInternals\\Core\\ModuleStateFixer->__construct()\n#3 /var/www/oxid/source/oxfunctions.php(101): OxidEsales\\EshopCommunity\\Core\\UtilsObject->oxNew('OxidCommunity\\\\M...')\n#4 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/Registry.php(403): oxNew('OxidCommunity\\\\M...')\n#5 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/Registry.php(419): OxidEsales\\EshopCommunity\\Core\\Registry::createObject('OxidCommunity\\\\M...')\n#6 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/Registry.php(46): OxidEsales\\EshopCommunity\\Core\\Registry::getObject('OxidCommunity\\\\M...')\n#7 /var/www/oxid/source/modules/oxcom/moduleinternals/Core/InternalModule.php(497): OxidEsales\\EshopCommunity\\Core\\Registry::get('OxidCommunity\\\\M...')\n#8 /var/www/oxid/source/modules/oxcom/moduleinternals/Core/InternalModule.php(683): OxidCommunity\\ModuleInternals\\Core\\InternalModule->checkModuleController()\n#9 /var/www/oxid/source/modules/oxcom/moduleinternals/Core/InternalModule.php(196): OxidCommunity\\ModuleInternals\\Core\\InternalModule->checkState()\n#10 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/Module/ModuleList.php(637): OxidCommunity\\ModuleInternals\\Core\\InternalModule->getTitle()\n#11 [internal function]: OxidEsales\\EshopCommunity\\Core\\Module\\ModuleList->_sortModules(Object(OxidCommunity\\ModuleInternals\\Core\\InternalModule), Object(OxidCommunity\\ModuleInternals\\Core\\InternalModule))\n#12 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/Module/ModuleList.php(572): uasort(Array, Array)\n#13 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/Module/ModuleList.php(540): OxidEsales\\EshopCommunity\\Core\\Module\\ModuleList->getModulesFromDir('/var/www/oxid/s...', 'bestit')\n#14 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Application/Controller/Admin/ModuleList.php(34): OxidEsales\\EshopCommunity\\Core\\Module\\ModuleList->getModulesFromDir('/var/www/oxid/s...')\n#15 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(453): OxidEsales\\EshopCommunity\\Application\\Controller\\Admin\\ModuleList->render()\n#16 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(344): OxidEsales\\EshopCommunity\\Core\\ShopControl->_render(Object(OxidEsales\\Eshop\\Application\\Controller\\Admin\\ModuleList))\n#17 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(276): OxidEsales\\EshopCommunity\\Core\\ShopControl->formOutput(Object(OxidEsales\\Eshop\\Application\\Controller\\Admin\\ModuleList))\n#18 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(137): OxidEsales\\EshopCommunity\\Core\\ShopControl->_process('OxidEsales\\\\Esho...', NULL, NULL, NULL)\n#19 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Core/Oxid.php(26): OxidEsales\\EshopCommunity\\Core\\ShopControl->start()\n#20 /var/www/oxid/source/index.php(15): OxidEsales\\EshopCommunity\\Core\\Oxid::run()\n#21 /var/www/oxid/source/admin/index.php(11): require_once('/var/www/oxid/s...')\n#22 {main}\n"] []
```

**Comment by smxsm** [comment]
Yep, this is "breaking" our Oxid Backends currently, too :( Can't use the module management because of this exception ...

**Comment by keywan-ghadami-oxid** [comment]
workaround for this is to install the oxid console
```composer require oxid-professional-services/oxid-console```

**Comment by smxsm** [comment]
Yes, I know, but we already use oxrun :) We are downgrading / pinning to 1.0.x for now, at least for auto-deployed shops

**Comment by keywan-ghadami-oxid** [comment]
status:
seams to have a wrong use statement in https://github.com/OXIDprojects/oxid-module-internals/blob/master/Core/ModuleStateFixer.php#L13
